server.port=8083

spring.application.name=order-service

user.service.url=http://localhost:8084

app.message=Hello from Order Service TEST

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=test

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.userService.sliding-window-size=3
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.userService.automatic-transition-from-open-to-half-open-enabled=true

# Resilience4j Retry
resilience4j.retry.instances.userService.max-attempts=1
resilience4j.retry.instances.userService.wait-duration=1s

# Resilience4j Time Limiter
resilience4j.timelimiter.instances.userService.timeout-duration=2s
resilience4j.timelimiter.instances.userService.cancel-running-future=true